emp:
  lastName: 李四
  age: 28
  salary: 20000
  boss: true
  birthday: 1991/10/10
  map:
    key1: value1
    key2: value2
  list:
  - one
  - two
  - three
  forte:
    name: java
    time: 8


logging:
  config: classpath:log4j2-prod.xml

# thymeleaf模板
spring:
  profiles:
    active: dev
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    check-template-location: true
    suffix: .html
    encoding: UTF-8
    mode: HTML
# 静态资源配置
# spring.resources.static-locations=classpath:/hello/,classpath:/other/

